### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by paulmillr** [chiefbiiko/sha256#4]
error: TS2564 [ERROR]: Property '_bufIdx' has no initializer and is not definitely assigned in the constructor.
  private _bufIdx: number;
          ~~~~~~~
    at https://raw.githubusercontent.com/chiefbiiko/sha256/v1.0.0/mod.ts:14:11

TS2564 [ERROR]: Property '_count' has no initializer and is not definitely assigned in the constructor.
  private _count: Uint32Array;
          ~~~~~~
    at https://raw.githubusercontent.com/chiefbiiko/sha256/v1.0.0/mod.ts:15:11

TS2564 [ERROR]: Property '_H' has no initializer and is not definitely assigned in the constructor.
  private _H: Uint32Array;
          ~~
    at https://raw.githubusercontent.com/chiefbiiko/sha256/v1.0.0/mod.ts:17:11

TS2564 [ERROR]: Property '_finalized' has no initializer and is not definitely assigned in the constructor.
  private _finalized: boolean;
          ~~~~~~~~~~
    at https://raw.githubusercontent.com/chiefbiiko/sha256/v1.0.0/mod.ts:18:11

**Comment by chisNaN** [comment]
it has been merged into standard library with another implementation
the PR => https://github.com/denoland/deno/pull/5066/
the official doc => https://deno.land/std/hash
(replace md5 with sha256)
